### ISSUE TITLE
graph-store update broke discord -> urbit

### ISSUE THREAD

**Issue by ryjm** [midsum-salrux/faux-legacy#2]
probably just need to update the update mark

**Comment by midsum-salrux** [comment]
This should be fixed by the most recent quinnat (chatbot library) update. Are you running quinnat 1.0.5?

https://github.com/midsum-salrux/quinnat/commit/425df9af5c061b702ae229df1eea77db90961dbd

You can update with `pip3 install quinnat --upgrade`
